(#<PACKAGE "USER"> #<PACKAGE "SEQUENCE"> #<PACKAGE "PRECOMPILER"> #<PACKAGE "XP"> 
  #<PACKAGE "FORMAT"> #<PACKAGE "THREADS"> #<PACKAGE "LISP"> #<PACKAGE "JAVA">
  #<PACKAGE "PROFILER"> #<PACKAGE "LOOP"> #<PACKAGE "JVM"> #<PACKAGE "EXTENSIONS">
   #<PACKAGE "TOP-LEVEL"> #<PACKAGE "MOP"> #<PACKAGE "SYSTEM"> #<PACKAGE "COMMON-LISP-USER"> 
   #<PACKAGE "COMMON-LISP"> #<PACKAGE "CYC"> #<PACKAGE "SUBLISP"!> #<PACKAGE "KEYWORD">)

