

;;; Definitions for package SLOT-ACCESSOR-NAME of type ESTABLISH
(LISP::IN-PACKAGE "SLOT-ACCESSOR-NAME" :USE LISP::NIL :NICKNAMES
    '("S-A-N"))

;;; Definitions for package PCL of type ESTABLISH
(LISP::IN-PACKAGE "PCL" :USE LISP::NIL)

;;; Definitions for package ITERATE of type ESTABLISH
(LISP::IN-PACKAGE "ITERATE" :USE LISP::NIL)

;;; Definitions for package WALKER of type ESTABLISH
(LISP::IN-PACKAGE "WALKER" :USE LISP::NIL)

;;; Definitions for package SLOT-ACCESSOR-NAME of type EXPORT
(LISP::IN-PACKAGE "SLOT-ACCESSOR-NAME" :USE 'LISP::NIL :NICKNAMES
    '("S-A-N"))
(LISP::IMPORT 'LISP::NIL)
(LISP::EXPORT 'LISP::NIL)

;;; Definitions for package PCL of type EXPORT
(LISP::IN-PACKAGE "PCL" :USE '("LISP" "ITERATE" "WALKER"))
(LISP::IMPORT 'LISP::NIL)
(LISP::EXPORT
    '(PCL::CLASS-PRECEDENCE-LIST PCL::SLOT-DEFINITION
         PCL::COMPUTE-APPLICABLE-METHODS-USING-CLASSES
         PCL::SLOT-DEFINITION-WRITERS PCL::CLASS-OF
         PCL::NO-APPLICABLE-METHOD PCL::STANDARD-WRITER-METHOD
         PCL::ENSURE-CLASS-USING-CLASS PCL::ENSURE-GENERIC-FUNCTION
         PCL::FIND-METHOD-COMBINATION PCL::MAP-DEPENDENTS
         PCL::SLOT-MISSING PCL::SPECIALIZER PCL::CALL-NEXT-METHOD
         PCL::ENSURE-GENERIC-FUNCTION-USING-CLASS
         PCL::SLOT-MAKUNBOUND-USING-CLASS PCL::MAKE-INSTANCES-OBSOLETE
         PCL::INTERN-EQL-SPECIALIZER PCL::REMOVE-DIRECT-SUBCLASS
         PCL::METHOD-GENERIC-FUNCTION PCL::METHOD-QUALIFIERS
         PCL::FUNCALLABLE-STANDARD-CLASS PCL::EXTRACT-LAMBDA-LIST
         PCL::STANDARD-CLASS PCL::PRINT-OBJECT PCL::STRUCTURE-CLASS
         PCL::COMPUTE-EFFECTIVE-SLOT-DEFINITION
         PCL::GENERIC-FUNCTION-DECLARATIONS PCL::MAKE-INSTANCE
         PCL::METHOD-LAMBDA-LIST PCL::DEFGENERIC
         PCL::REMOVE-DIRECT-METHOD PCL::STANDARD-DIRECT-SLOT-DEFINITION
         PCL::GENERIC-FUNCTION-METHODS PCL::VALIDATE-SUPERCLASS
         PCL::REINITIALIZE-INSTANCE PCL::SLOT-EXISTS-P-USING-CLASS
         PCL::STANDARD-METHOD PCL::STANDARD-ACCESSOR-METHOD
         PCL::FUNCALLABLE-STANDARD-INSTANCE PCL::FUNCTION-KEYWORDS
         PCL::STANDARD PCL::FIND-METHOD PCL::EXTRACT-SPECIALIZER-NAMES
         PCL::INITIALIZE-INSTANCE PCL::GENERIC-FLET PCL::SLOT-UNBOUND
         PCL::STANDARD-INSTANCE PCL::SLOT-DEFINITION-TYPE
         PCL::COMPUTE-EFFECTIVE-METHOD PCL::ALLOCATE-INSTANCE
         PCL::SYMBOL-MACROLET PCL::GENERIC-FUNCTION
         PCL::GENERIC-FUNCTION-METHOD-COMBINATION
         PCL::SPECIALIZER-DIRECT-METHODS PCL::ADD-DIRECT-SUBCLASS
         PCL::WRITER-METHOD-CLASS PCL::SLOT-DEFINITION-INITARGS
         PCL::METHOD-SPECIALIZERS PCL::GENERIC-FUNCTION-METHOD-CLASS
         PCL::ADD-METHOD PCL::WITH-ACCESSORS
         PCL::SLOT-DEFINITION-ALLOCATION
         PCL::SLOT-DEFINITION-INITFUNCTION
         PCL::SLOT-DEFINITION-LOCATION PCL::ADD-DIRECT-METHOD
         PCL::SLOT-BOUNDP PCL::EQL-SPECIALIZER PCL::SHARED-INITIALIZE
         PCL::STANDARD-GENERIC-FUNCTION
         PCL::ACCESSOR-METHOD-SLOT-DEFINITION
         PCL::SLOT-BOUNDP-USING-CLASS PCL::ADD-DEPENDENT
         PCL::SPECIALIZER-DIRECT-GENERIC-FUNCTION
         PCL::WITH-ADDED-METHODS PCL::COMPUTE-CLASS-PRECEDENCE-LIST
         PCL::REMOVE-DEPENDENT PCL::NEXT-METHOD-P
         PCL::GENERIC-FUNCTION-NAME PCL::SLOT-VALUE
         PCL::EFFECTIVE-SLOT-DEFINITION PCL::CLASS-FINALIZED-P
         PCL::COMPUTE-DISCRIMINATING-FUNCTION PCL::STANDARD-OBJECT
         PCL::CLASS-DEFAULT-INITARGS PCL::CLASS-DIRECT-SLOTS
         PCL::FUNCALLABLE-STANDARD-INSTANCE-ACCESS PCL::BUILT-IN-CLASS
         PCL::NO-NEXT-METHOD PCL::SLOT-MAKUNBOUND
         PCL::STANDARD-READER-METHOD PCL::GENERIC-FUNCTION-LAMBDA-LIST
         PCL::GENERIC-FUNCTION-ARGUMENT-PRECEDENCE-ORDER
         PCL::INVALID-METHOD-ERROR PCL::METHOD-COMBINATION-ERROR
         PCL::SLOT-EXISTS-P PCL::FINALIZE-INHERITANCE
         PCL::SLOT-DEFINITION-NAME
         PCL::STANDARD-EFFECTIVE-SLOT-DEFINITION PCL::COMPUTE-SLOTS
         PCL::CLASS-SLOTS PCL::EFFECTIVE-SLOT-DEFINITION-CLASS
         PCL::STANDARD-INSTANCE-ACCESS PCL::WITH-SLOTS
         PCL::DIRECT-SLOT-DEFINITION PCL::DEFINE-METHOD-COMBINATION
         PCL::MAKE-METHOD-LAMBDA PCL::ENSURE-CLASS
         PCL::DIRECT-SLOT-DEFINITION-CLASS PCL::METHOD-FUNCTION
         PCL::STANDARD-SLOT-DEFINITION PCL::CHANGE-CLASS PCL::DEFMETHOD
         PCL::UPDATE-INSTANCE-FOR-DIFFERENT-CLASS
         PCL::UPDATE-INSTANCE-FOR-REDEFINED-CLASS
         PCL::FORWARD-REFERENCED-CLASS PCL::SLOT-DEFINITION-INITFORM
         PCL::REMOVE-METHOD PCL::READER-METHOD-CLASS PCL::CALL-METHOD
         PCL::CLASS-PROTOTYPE PCL::CLASS-NAME PCL::FIND-CLASS
         PCL::DEFCLASS PCL::COMPUTE-APPLICABLE-METHODS
         PCL::DESCRIBE-OBJECT PCL::SLOT-VALUE-USING-CLASS
         PCL::METHOD-COMBINATION PCL::EQL-SPECIALIZER-INSTANCE
         PCL::GENERIC-LABELS PCL::METHOD PCL::SLOT-DEFINITION-READERS
         PCL::CLASS-DIRECT-DEFAULT-INITARGS
         PCL::CLASS-DIRECT-SUBCLASSES PCL::CLASS-DIRECT-SUPERCLASSES
         PCL::SET-FUNCALLABLE-INSTANCE-FUNCTION))

;;; Definitions for package ITERATE of type EXPORT
(LISP::IN-PACKAGE "ITERATE" :USE '("WALKER" "LISP"))
(LISP::IMPORT 'LISP::NIL)
(LISP::EXPORT
    '(ITERATE::SUMMING ITERATE::MINIMIZING ITERATE::PLIST-ELEMENTS
         ITERATE::ITERATE* ITERATE::MAXIMIZING ITERATE::LIST-TAILS
         ITERATE::*ITERATE-WARNINGS* ITERATE::GATHERING
         ITERATE::EACHTIME ITERATE::ELEMENTS ITERATE::GATHER
         ITERATE::LIST-ELEMENTS ITERATE::WHILE ITERATE::ITERATE
         ITERATE::UNTIL ITERATE::JOINING ITERATE::COLLECTING
         ITERATE::WITH-GATHERING ITERATE::INTERVAL))

;;; Definitions for package WALKER of type EXPORT
(LISP::IN-PACKAGE "WALKER" :USE '("LISP"))
(LISP::IMPORT 'LISP::NIL)
(LISP::EXPORT
    '(WALKER::DEFINE-WALKER-TEMPLATE WALKER::*VARIABLE-DECLARATIONS*
         WALKER::NESTED-WALK-FORM WALKER::VARIABLE-DECLARATION
         WALKER::WALK-FORM-EXPAND-MACROS-P WALKER::VARIABLE-LEXICAL-P
         WALKER::VARIABLE-SPECIAL-P WALKER::WALK-FORM
         WALKER::VARIABLE-GLOBALLY-SPECIAL-P))

;;; Definitions for package SLOT-ACCESSOR-NAME of type SHADOW
(LISP::IN-PACKAGE "SLOT-ACCESSOR-NAME")
(LISP::SHADOW 'LISP::NIL)
(LISP::SHADOWING-IMPORT 'LISP::NIL)
(LISP::IMPORT 'LISP::NIL)

;;; Definitions for package PCL of type SHADOW
(LISP::IN-PACKAGE "PCL")
(LISP::SHADOW '(PCL::DOTIMES PCL::DOCUMENTATION))
(LISP::SHADOWING-IMPORT 'LISP::NIL)
(LISP::IMPORT '(SYSTEM::STRUCTUREP))

;;; Definitions for package ITERATE of type SHADOW
(LISP::IN-PACKAGE "ITERATE")
(LISP::SHADOW 'LISP::NIL)
(LISP::SHADOWING-IMPORT 'LISP::NIL)
(LISP::IMPORT 'LISP::NIL)

;;; Definitions for package WALKER of type SHADOW
(LISP::IN-PACKAGE "WALKER")
(LISP::SHADOW 'LISP::NIL)
(LISP::SHADOWING-IMPORT 'LISP::NIL)
(LISP::IMPORT 'LISP::NIL)

(in-package 'SI)
(export '(%structure-name
          %compiled-function-name
          %set-compiled-function-name))
(in-package 'pcl)
