
(IN-PACKAGE "PCL") 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM T FIXNUM) FIXNUM)
            COMPUTE-PRIMARY-CACHE-LOCATION-FROM-LOCATION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FIXNUM) ARG-INFO-NUMBER-REQUIRED
            COUNT-NON-NILS CHECKING-LIMIT-FN CACHE-COUNT
            N-N-ACCESSORS-LIMIT-FN ARG-INFO-NKEYS CACHING-LIMIT-FN
            WRAPPER-FIELD ONE-INDEX-LIMIT-FN CPD-COUNT)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM) T) NEXT-WRAPPER-FIELD DFUN-ARG-SYMBOL
            SLOT-VECTOR-SYMBOL ALLOCATE-CACHE-VECTOR)) 
(PROCLAIM '(FTYPE (FUNCTION (T) FIELD-TYPE) CACHE-FIELD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) LIST) INTERNAL-SLOTD-INITARGS CACHE-OVERFLOW)) 
(PROCLAIM '(FTYPE (FUNCTION (T) REAL-FUNCTION) CACHE-LIMIT-FN)) 
(PROCLAIM '(FTYPE (FUNCTION (T) SIMPLE-VECTOR) CACHE-VECTOR)) 
(PROCLAIM '(FTYPE (FUNCTION (T) SYMBOL) INTERNAL-SLOTD-NAME)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (VALUES T T)) MAKE-CLASS-PREDICATE-NAME
            MAKE-KEYWORD LAP-REG GET-METHOD-FROM-IDENTIFIER
            METHOD-FUNCTION-PLIST DEFSTRUCT-FORM)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM T) T) MAKE-CAXR MAKE-CDXR
            %CCLOSURE-ENV-NTHCDR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM FIXNUM T) FIXNUM)
            COMPUTE-PRIMARY-CACHE-LOCATION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM) FIXNUM) COMPUTE-LINE-SIZE
            POWER-OF-TWO-CEILING DEFAULT-LIMIT-FN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) INDEX) CACHE-NLINES CACHE-MASK
            CACHE-MAX-LOCATION CACHE-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 512)) CACHE-LINE-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 256)) CACHE-NKEYS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (OR INDEX NULL)) ARG-INFO-NUMBER-OPTIONAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (OR FUNCTION NULL))
            INTERNAL-SLOTD-INITFUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) *) GET-EFFECTIVE-METHOD-FUNCTION
            SLOT-VALUE-OR-DEFAULT COMPUTE-SECONDARY-DISPATCH-FUNCTION
            MAKE-DOCUMENTED-STANDARD-METHOD-LAMBDA MAKE-ACCESSOR-TABLE
            LOAD-DEFGENERIC MAKE-EFFECTIVE-METHOD-FUNCTION
            MAKE-CHECKING-DFUN MAKE-N-N-ACCESSOR-DFUN
            TYPES-FROM-ARGUMENTS NESTED-WALK-FORM)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) ITERATE::EXPAND-INTO-LET
            CONSTANT-VALUE-MISS MAKE-FINAL-N-N-ACCESSOR-DFUN
            MAKE-FINAL-CACHING-DFUN LOAD-LONG-DEFCOMBIN
            ITERATE::RENAME-VARIABLES
            GET-OPTIMIZED-STD-ACCESSOR-METHOD-FUNCTION
            GET-OPTIMIZED-STD-READER-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-WRITER-METHOD-FUNCTION
            GET-OPTIMIZED-STD-WRITER-METHOD-FUNCTION
            GET-OPTIMIZED-STD-BOUNDP-METHOD-FUNCTION SET-SLOT-VALUE
            MAKE-OPTIMIZED-STD-READER-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-BOUNDP-METHOD-FUNCTION
            SLOT-VALUE-USING-CLASS-DFUN CONVERT-METHODS
            WALKER::WALK-FORM-INTERNAL
            GENERATE-DISCRIMINATION-NET-INTERNAL-DO-COLUMN
            NET-CODE-CONVERTER CACHE-MISS-VALUES
            ITERATE::WALK-GATHERING-BODY SLOT-BOUNDP-USING-CLASS-DFUN
            CHECKING-MISS ACCESSOR-VALUES WALKER::WALK-LET-IF
            MAKE-FINAL-CONSTANT-VALUE-DFUN CACHING-MISS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) *)
            ITERATE::ITERATE-TRANSFORM-BODY EXPAND-DEFMETHOD-INTERNAL
            MAKE-LAP-CLOSURE-GENERATOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *) SIMPLE-SLOTS-GENERATOR-INTERNAL
            ORDER-SPECIALIZERS MAKE-ONE-CLASS-ACCESSOR-DFUN
            GET-ACCESSOR-METHOD-FUNCTION LOAD-SHORT-DEFCOMBIN
            GENERATE-DISCRIMINATION-NET MAKE-FINAL-CHECKING-DFUN
            FINALIZE-LAP-GENERATION EARLY-MAKE-METHOD-LAMBDA
            MAKE-METHOD-LAMBDA-AND-OPTIMIZED-LAMBDA
            NO-METHODS-GENERATOR-INTERNAL
            SETF-SLOT-VALUE-USING-CLASS-DFUN
            MAKE-OPTIMIZED-STANDARD-METHOD-LAMBDA
            MAKE-FINAL-ONE-INDEX-ACCESSOR-DFUN ACCESSOR-MISS
            MAKE-ACCESSOR-FROM-SVUC-METHOD-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) *)
            COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO-INTERNAL
            MAKE-TWO-CLASS-ACCESSOR-DFUN
            GENERATE-DISCRIMINATION-NET-INTERNAL-DO-METHODS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) *) WALKER::WALK-DECLARATIONS
            GET-SECONDARY-DISPATCH-FUNCTION
            MAKE-ONE-INDEX-ACCESSOR-DFUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) *) ITERATE::RENAME-LET-BINDINGS
            NO-SLOT-ACCESSOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) *)
            GENERATE-DISCRIMINATION-NET-INTERNAL
            MAKE-LONG-METHOD-COMBINATION-FUNCTION
            GENERAL-GENERATOR-INTERNAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T) *)
            BOOTSTRAP-INITIALIZE-STRUCTURE-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T) *)
            BOOTSTRAP-INITIALIZE-BUILT-IN-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) BOOLEAN) CACHE-VALUEP
            GF-PRECOMPUTE-DFUN-AND-EMF-P GF-INFO-C-A-M-EMF-STD-P
            ARG-INFO-KEY/REST-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) COMPILED-FUNCTION)
            INTERNAL-SLOTD-READER-FUNCTION
            INTERNAL-SLOTD-WRITER-FUNCTION
            INTERNAL-SLOTD-BOUNDP-FUNCTION)) 
(PROCLAIM '(FTYPE (FUNCTION (T STREAM T) T) PRINT-DFUN-INFO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) T) EMIT-GET-CLASS-SLOT
            EMIT-SET-CLASS-SLOT DEFOPCODE-1 CPL-ERROR
            WALKER::CONVERT-MACRO-TO-LAMBDA
            ENSURE-GENERIC-FUNCTION-USING-CLASS PROCLAIM-FUNCTION
            RECORD-DEFINITION DEFOPERAND-1 PROBE-CACHE
            REAL-ENSURE-GF-USING-CLASS--GENERIC-FUNCTION
            REAL-ENSURE-GF-USING-CLASS--NULL MAP-CACHE
            FIND-CLASS-PREDICATE-FROM-CELL NAMED-OBJECT-PRINT-FUNCTION
            GET-EFFECTIVE-METHOD-FUNCTION1 PLIST-VALUE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T *) T) EARLY-MAKE-A-METHOD
            REAL-MAKE-A-METHOD EARLY-ADD-NAMED-METHOD
            REAL-ADD-NAMED-METHOD)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T FIXNUM) T) FILL-CACHE-FROM-CACHE-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T T T T T) T)
            ADD-LEXICAL-FUNCTIONS-TO-OPTIMIZED-STANDARD-METHOD-LAMBDA)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T T T T *) T) EMIT-DLAP)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T) T) LOAD-DEFMETHOD-INTERNAL
            LOAD-DEFMETHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T T T T) T)
            BOOTSTRAP-INITIALIZE-STANDARD-CLASS)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T FIXNUM T T *) T) SET-ARG-INFO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T T T T T T) T)
            ADD-LEXICAL-FUNCTIONS-TO-DOCUMENTED-STANDARD-METHOD-LAMBDA)) 
(PROCLAIM '(FTYPE (FUNCTION (T T FIXNUM) T) COMPUTE-STD-CPL-PHASE-3)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) T) EXPAND-DEFMETHOD
            MAKE-LAP-CLOSURE-GENERATOR-LAMBDA)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T)
            |CONSTRUCTOR-CODE-GENERATOR PCL SIMPLE-SLOTS|
            LOAD-CONSTRUCTOR MAKE-FINAL-ORDINARY-DFUN-INTERNAL
            BOOTSTRAP-MAKE-SLOT-DEFINITIONS MAKE-LAP-PROG
            EMIT-1-NIL-DLAP DLAP-WRAPPER-MOVES OPTIMIZE-SLOT-VALUE
            OPTIMIZE-SET-SLOT-VALUE OPTIMIZE-SLOT-BOUNDP
            GET-SECONDARY-DISPATCH-FUNCTION2
            |CONSTRUCTOR-CODE-GENERATOR PCL GENERAL|
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT
            MAKE-PARAMETER-REFERENCES
            |CONSTRUCTOR-CODE-GENERATOR PCL NO-METHODS|
            |CONSTRUCTOR-CODE-GENERATOR PCL FALLBACK|
            WALKER::WALK-BINDINGS-1 MAKE-LAP-PROG-INTERNAL
            MAKE-EMF-CACHE BUILD-WITH-ACCESSOR-S-V MAKE-FGEN
            LOAD-FUNCTION-GENERATOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T) SYSTEM::APPLY-DISPLAY-FUN
            PRINT-INTERNAL-SLOTD ONE-INDEX-DFUN-INFO |LAP Opcode NEQ|
            WALKER::WALK-DO* CHECK-OPCODE-ARG WALKER::WALK-IF
            EMIT-1-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            GET-NEW-FUNCTION-GENERATOR CHECK-INITARGS-1
            SET-FUNCALLABLE-STANDARD-INSTANCE-ACCESS MAKE-SLOT-SYMBOL
            SORT-METHODS ITERATE::OPTIMIZE-GATHERING-FORM
            SORT-APPLICABLE-METHODS
            ITERATE::SIMPLE-EXPAND-GATHERING-FORM
            WRAP-METHOD-GROUP-SPECIFIER-BINDINGS
            EARLY-STORE-METHOD-FUNCTION-P SET-FUNCTION-NAME-1
            EARLY-STORE-METHOD-OPTIMIZED-FUNCTION-P
            EARLY-STORE-CLOSURE-GENERATOR-P PRINT-STD-INSTANCE
            TRACE-FUNCTION-INTERNAL WALKER::WALK-SETQ MAKE-METHOD-SPEC
            OPTIMIZE-SLOT-VALUE-BY-CLASS-P
            ITERATE::OPTIMIZE-ITERATE-FORM SET-STANDARD-INSTANCE-ACCESS
            WALKER::WALK-FLET |LAP Opcode EQ| WALKER::WALK-PROG
            SKIP-FAST-SLOT-ACCESS-P SKIP-OPTIMIZE-SLOT-VALUE-BY-CLASS-P
            CHECK-OPERAND-ARG WALKER::WALK-MULTIPLE-VALUE-BIND
            WALKER::WALK-LABELS WALKER::WALK-TAGBODY-1
            |LAP Opcode FIX=| WALKER::WALK-SYMBOL-MACROLET
            WALKER::WALK-PROG* SET-USER-INSTANCE-ACCESS
            WALKER::WALK-LAMBDA FLUSH-CACHE-TRAP BOOTSTRAP-GET-SLOT
            OBSOLETE-INSTANCE-TRAP UPDATE-STRUCTURE-CLASS
            WALKER::WALK-TAGBODY |SETF PCL METHOD-FUNCTION-GET|
            FIX-SLOT-ACCESSORS |SETF PCL PLIST-VALUE|
            WALKER::WALK-NAMED-LAMBDA SLOW-SET-SLOT-VALUE
            WALKER::WALK-COMPILER-LET WALKER::WALK-LET
            |LAP Operand ISET| WALKER::WALK-MULTIPLE-VALUE-SETQ
            WALKER::RELIST-INTERNAL CAN-OPTIMIZE-ACCESS
            ITERATE::VARIABLE-SAME-P OPTIMIZE-GENERIC-FUNCTION-CALL
            GET-FUNCTION-GENERATOR EMIT-LOCK-COUNT-TEST
            ONE-CLASS-DFUN-INFO WALKER::RECONS WALKER::WALK-LET*
            MAKE-TOP-LEVEL-FORM WALKER::WALK-MACROLET MAP-ALL-ORDERS
            EXPAND-DEFGENERIC SET-CONSTRUCTOR-CODE INVALIDATE-WRAPPER
            EMIT-CHECK-1-CLASS-WRAPPER
            WALKER::WITH-AUGMENTED-ENVIRONMENT-INTERNAL
            EARLY-STORE-OPTIMIZED-METHOD-LAMBDA-P CONVERT-TABLE
            MAKE-DFUN-CALL
            EMIT-N-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            NEW-ARG-INFO-FROM-GENERIC-FUNCTION COMPUTE-PRECEDENCE
            WALKER::WALK-DO ITERATE::RENAME-AND-CAPTURE-VARIABLES
            PRINT-CACHE WALKER::WALK-UNEXPECTED-DECLARE
            VARIABLE-DECLARATION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T)
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT-1
            BOOTSTRAP-MAKE-SLOT-DEFINITION MAKE-EARLY-CLASS-DEFINITION
            LOAD-DEFCLASS EMIT-DLAP-INTERNAL EMIT-ADJUST-LOCATION
            EMIT-GREATER-THAN-1-DLAP EMIT-1-T-DLAP
            OPTIMIZE-STD-INSTANCE-ACCESS REAL-LOAD-DEFCLASS
            DO-SHORT-METHOD-COMBINATION BUILD-MAYBE-SAFE-W-O-S-V)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T) ADJUST-CACHE EXPAND-CACHE
            MAKE-STD-CLOSURE-GENERATOR-FORM WALKER::WALK-BINDINGS-2
            EXPAND-SYMBOL-MACROLET-INTERNAL
            EMIT-CHECK-1-WRAPPER-IN-CACHE CHECK-INITARGS
            BUILD-W-S-V-FIND-SLOT-INDICES EMIT-CHECK-2-CLASS-WRAPPER
            GET-ACCESSOR-FROM-SVUC-METHOD-FUNCTION TWO-CLASS-DFUN-INFO
            EXPAND-DEFCLASS LOAD-PRECOMPILED-DFUN-CONSTRUCTOR
            WALKER::WALK-LET/LET* MAKE-CONSTRUCTOR BOOTSTRAP-SET-SLOT
            WALKER::WALK-TEMPLATE EXPAND-DEFCONSTRUCTOR
            WALKER::WALK-PROG/PROG* EMIT-CHECK-CACHE-LINE
            BOOTSTRAP-ACCESSOR-DEFINITIONS EMIT-CHECK-CACHE-ENTRY
            WALKER::WALK-DO/DO* FILL-CACHE-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) T) EMIT-FETCH-WRAPPER
            FILL-DFUN-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) T) GET-METHOD FILL-CACHE
            REAL-GET-METHOD EMIT-GET-SLOT EMIT-SET-SLOT
            BUILD-WITH-OPTIMIZED-SLOTS-FORM
            GET-SECONDARY-DISPATCH-FUNCTION1 WALKER::WALK-ARGLIST
            RECORD-UPDATER)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM FIXNUM) FIXNUM) MAKE-INDEX-MASK)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) RENEW-SYS-FILES EMIT-N-N-READERS
            COUNT-ALL-DFUNS EMIT-N-N-WRITERS)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) IN-THE-COMPILER-P RESET-CONSTRUCTORS
            BEFORE-PRECOMPILE-RANDOM-CODE-SEGMENTS BOOTSTRAP-META-BRAID
            DEFAULT-METHOD-ONLY-DFUN-INFO MAKE-ARG-INFO
            |LAP Opcode EXIT-LAP-IN-LISP| DISABLE-CONSTRUCTORS
            RESET-PCL-PACKAGE SHOW-FREE-CACHE-VECTORS
            INITIAL-DISPATCH-DFUN-INFO FLOAT-ZERO
            SHOW-DFUN-CONSTRUCTORS |LAP Opcode BREAK|
            ENABLE-CONSTRUCTORS EARLY-INITIALIZE-SLOT-GFS
            %%ALLOCATE-INSTANCE--CLASS CACHES-TO-ALLOCATE
            ALLOCATE-FUNCALLABLE-INSTANCE-1
            ALLOCATE-FUNCALLABLE-INSTANCE-2 MAKE-CPD
            GET-EFFECTIVE-METHOD-GENSYM DISPATCH-DFUN-INFO
            FIX-DFUNS-NEEDING-UPDATE NO-METHODS-DFUN-INFO
            |LAP Opcode BEEP| MAKE-CACHE BOOTSTRAP-BUILT-IN-CLASSES
            EARLY-INITIALIZE-CLASS-PREDICATES LIST-ALL-DFUNS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) *) INVALID-METHOD-ERROR
            METHOD-COMBINATION-ERROR UNTRACE-METHOD
            FINALIZE-ALL-CLASSES LIST-LARGE-CACHES)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T T) *) COMPUTE-CACHE-PARAMETERS)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T *) *) FIND-FREE-CACHE-LINE)) 
(PROCLAIM '(FTYPE (FUNCTION (T FIXNUM T) *) EMIT-READER/WRITER)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) |__si::MAKE-TWO-CLASS| TRUE
            |__si::MAKE-ONE-INDEX-DFUN-INFO| WRAPPER-ERROR
            |__si::MAKE-ARG-INFO| |__si::MAKE-STD-INSTANCE|
            |__si::MAKE-CHECKING| |__si::MAKE-CACHING|
            WALKER::UNBOUND-LEXICAL-FUNCTION |__si::MAKE-NO-METHODS|
            |__si::MAKE-CLASS-PRECEDENCE-DESCRIPTION| FALSE
            FIX-EARLY-GENERIC-FUNCTIONS |__si::MAKE-N-N|
            |__si::MAKE-DEFAULT-METHOD-ONLY| FLATTEN-LAP
            |__si::MAKE-CONSTANT-VALUE| STRING-APPEND
            NULL-WRAPPERS-METHOD-FUNCTION |__si::MAKE-INITIAL-DISPATCH|
            |STRUCTURE-OBJECT class constructor|
            CALLED-FIN-WITHOUT-FUNCTION |__si::MAKE-DISPATCH|
            |__si::MAKE-ONE-CLASS| MAKE-PROGN
            |__si::MAKE-ACCESSOR-DFUN-INFO| |__si::MAKE-ONE-INDEX| ZERO
            MAKE-INTERNAL-SLOTD |__si::MAKE-DFUN-INFO|
            |__si::MAKE-CACHE|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) IN-COMPILER-FORCE-COMPILE
            SLOT-INITFUNCTION-STORAGE-FORM COMPILE-INITFUNCTION
            MAKE-DISPATCH-DFUN EMIT-CONSTANT-VALUE
            COMPUTE-APPLICABLE-METHODS-EMF MAKE-FINAL-DISPATCH-DFUN
            PARSE-METHOD-GROUP-SPECIFIER ANALYZE-LAMBDA-LIST
            PARSE-DEFMETHOD EMIT-ONE-CLASS-READER PCL-DESCRIBE
            COMPUTE-CONSTANT-VECTOR EMIT-ONE-INDEX-READERS
            EMIT-ONE-CLASS-WRITER EMIT-ONE-INDEX-WRITERS
            MAP-CONSTRUCTORS METHOD-FUNCTION-STORAGE-FORM
            COMPILE-FUNCTION EMIT-TWO-CLASS-READER
            DEFAULT-CODE-CONVERTER EARLY-COLLECT-INHERITANCE
            EMIT-TWO-CLASS-WRITER GET-DISPATCH-FUNCTION CCLOSUREP)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM T T T) T) GET-WRAPPERS-FROM-CLASSES)) 
(PROCLAIM '(FTYPE (FUNCTION (T FIXNUM *) T) GET-CACHE-FROM-CACHE)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T T FIXNUM) T) GET-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) SIMPLE-EVAL-ACCESS-P UNDEFMETHOD-1
            ALL-STANDARD-ACCESSES-P MAP-ALL-GENERIC-FUNCTIONS
            |LAP Operand WRAPPER-CACHE-NUMBER-VECTOR|
            STRUCTURE-SLOTD-READER-FUNCTION LOOKUP-FGEN
            |LAP Operand OTHER-WRAPPER| TWO-CLASS-ACCESSOR-TYPE
            STORE-FGEN GFS-OF-TYPE DEFAULT-METHOD-ONLY-CACHE
            REALLY-FUNCTION-P METHOD-FUNCTION-METHOD
            FTYPE-DECLARATION-FROM-LAMBDA-LIST EARLY-COLLECT-CPL
            DFUN-INFO-P ARG-INFO-PRECEDENCE GET-WRITER-FUNCTION
            EARLY-METHOD-QUALIFIERS LAP-OPERAND CPD-CLASS
            TWO-CLASS-WRAPPER1 |LAP Opcode JMP| STORE-DEFSTRUCT-FORM
            FLUSH-CACHE-VECTOR-INTERNAL FREE-CACHE CACHE-P
            |LAP Operand LISP-VARIABLE| MAKE-STD-WRITER-METHOD-FUNCTION
            PROCLAIM-CLOSURE EXPAND-LONG-DEFCOMBIN ONE-CLASS-CACHE
            INITIALIZE-INTERNAL-SLOT-BOUNDP-GFS *NORMALIZE-TYPE
            MAKE-FIND-CLASS-CELL STRUCTURE-SLOTD-WRITER-FUNCTION
            FUNCTION-RETURNING-T DEFAULT-TEST-CONVERTER
            INTERNAL-SLOTD-SLOT-DEFINITION ECD-CLASS-NAME GBOUNDP
            CONSTANT-VALUE-CACHE CACHING-DFUN-INFO INTERNAL-SLOTD-P
            MAKE-TYPE-PREDICATE FUNCTION-FTYPE-DECLAIMED-P
            INTERNAL-SLOTD-LOCATION STRUCTURE-TYPE-INCLUDED-TYPE-NAME
            NET-TEST-CONVERTER UPDATE-ALL-C-A-M-GF-INFO
            SYSTEM::NEXT-STACK-FRAME EARLY-GF-NAME
            INITIAL-DISPATCH-CACHE FUNCALLABLE-INSTANCE-P
            TWO-CLASS-CACHE GDEFINITION EARLY-COLLECT-SLOTS
            NO-METHODS-P CACHING-P
            MAKE-STRUCTURE-INSTANCE-READER-METHOD-FUNCTION
            |LAP Operand CVAR| KNOWN-STRUCTURE-TYPE-P
            STRUCTURE-SLOTD-NAME UNTRACE-METHOD-FUNCTION-NAMES
            INDEX-VALUE->INDEX NON-PCL-SHARED-INITIALIZE-METHODS-P
            ONE-CLASS-ACCESSOR-TYPE EXPAND-SHORT-DEFCOMBIN
            CLASS-FROM-TYPE |LAP Opcode LABEL| ONE-CLASS-INDEX
            LIST-DFUN EARLY-CLASS-ORIGINAL-STATIC-SLOT-STORAGE-COPY
            TWO-CLASS-P GET-CACHE-VECTOR
            MAKE-FUNCALLABLE-STANDARD-INSTANCE-WRITER-METHOD-FUNCTION
            DEFAULT-CONSTANT-CONVERTER DEFSTRUCT-FORM-CLASS-NAME
            KEYWORD-SPEC-NAME ARG-INFO-APPLYP
            DEFSTRUCT-FORM-CONSTRUCTOR CONVERT-TO-SYSTEM-TYPE
            CLASS-PREDICATE DFUN-INFO-CACHE LAP-OPCODE
            EARLY-METHOD-FUNCTION MAKE-CLASS-PREDICATE
            USER-INSTANCE-SLOTS USE-CONSTANT-VALUE-DFUN-P
            FUNCTION-PRETTY-ARGLIST ECD-OTHER-INITARGS
            INTERN-FUNCTION-NAME CACHING-CACHE CLASS-STANDARD-P
            EARLY-METHOD-STANDARD-ACCESSOR-P |LAP Operand STD-WRAPPER|
            N-N-P STRUCTURE-OBJECT-P GF-INFO-STATIC-C-A-M-EMF
            PARSE-SPECIALIZERS ITERATE::VARIABLES-FROM-LET
            ALLOCATE-REGISTER CLASS-INSTANCE-TYPE
            UPDATE-GF-SIMPLE-ACCESSOR-TYPE DNET-METHODS-P
            DEFAULT-METHOD-ONLY-P FORCE-CACHE-FLUSHES
            |LAP Operand STD-SLOTS| |LAP Opcode RETURN|
            COMPILER::CAN-USE-PRINT-CIRCLE-P ECD-METACLASS N-N-CACHE
            REDIRECT-EARLY-FUNCTION-INTERNAL LAMBDA-LIST-REQUIRED-ARGS
            INITIALIZE-INTERNAL-SLOT-READER-GFS
            REALLY-COMPILED-FUNCTION-P |LAP Operand BUILT-IN-WRAPPER|
            MAKE-CLASS-EQ-PREDICATE ARG-INFO-METATYPES INSTANCE-TYPE
            CPD-AFTER DEFAULT-CONSTANTP
            INITIALIZE-INTERNAL-SLOT-WRITER-GFS TRACE-METHODS
            TWO-CLASS-INDEX NO-METHODS-CACHE
            EARLY-COLLECT-DEFAULT-INITARGS STRUCTURE-WRAPPER
            MAKE-OPTIMIZED-USER-BOUNDP-METHOD-FUNCTION DISPATCH-P
            UNPARSE-TYPE-LIST N-N-ACCESSOR-TYPE ACCESSOR-DFUN-INFO-P
            CLASS-PRECEDENCE-DESCRIPTION-P ONE-CLASS-WRAPPER0
            METHODS-CONTAIN-EQL-SPECIALIZER-P
            UPDATE-CLASS-CAN-PRECEDE-P TYPE-CLASS ARG-INFO-KEYWORDS
            FGEN-TEST MAKE-STD-READER-METHOD-FUNCTION
            DEFSTRUCT-FORM-CONC-NAME EMIT-MISS FREE-CACHE-VECTOR
            UNENCAPSULATED-FDEFINITION CHECK-WRAPPER-VALIDITY
            MAKE-EQL-PREDICATE UNPARSE-TYPE DLAP-WRAPPERS EARLY-GET-CPL
            FGEN-GENERATOR-LAMBDA STRUCTURE-TYPE-INTERNAL-SLOTDS
            CHECKING-P |LAP Operand ARG| FIND-CYCLE-REASONS CPD-SUPERS
            %CCLOSURE-ENV TWO-CLASS-WRAPPER0 COMPUTE-STD-CPL-PHASE-2
            WALKER::ENV-WALK-FUNCTION GET-BOUNDP-FUNCTION
            |LAP Operand STRUCTURE-WRAPPER| GET-READER-FUNCTION
            |LAP Operand REG| ARG-INFO-LAMBDA-LIST |LAP Operand I1+|
            DEFSTRUCT-FORM-PREDICATE-NAME ARG-INFO-VALID-P
            USER-INSTANCE-P WRAPPER-OF %STD-INSTANCE-WRAPPER
            INITIAL-DISPATCH-P
            MAKE-OPTIMIZED-USER-WRITER-METHOD-FUNCTION
            MAKE-DEFAULT-METHOD-GROUP-DESCRIPTION MAKE-INITIAL-DFUN
            GET-SETF-FUNCTION-NAME USER-INSTANCE-WRAPPER DISPATCH-CACHE
            |LAP Operand USER-WRAPPER| EXTRACT-LAMBDA-LIST
            UPDATE-GFS-OF-CLASS FIND-WRAPPER EXTRACT-SPECIALIZER-NAMES
            DEFAULT-SECONDARY-DISPATCH-FUNCTION FORMAT-CYCLE-REASONS
            FUNCTION-RETURNING-NIL DO-STANDARD-DEFSETFS-FOR-DEFCLASS
            ITERATE::SEQUENCE-ACCESSOR |LAP Operand LISP| EARLY-GF-P
            WALKER::ENV-LEXICAL-VARIABLES ONE-INDEX-DFUN-INFO-CACHE
            MAKE-STD-DOCUMENTED-METHOD-FUNCTION LEGAL-CLASS-NAME-P
            STANDARD-SVUC-METHOD GET-BUILT-IN-CLASS-SYMBOL
            METHOD-PROTOTYPE-FOR-GF |LAP Opcode GO|
            MAKE-STD-BOUNDP-METHOD-FUNCTION WALKER::ENV-DECLARATIONS
            DEALLOCATE-REGISTER WALKER::ENV-WALK-FORM UPDATE-GF-INFO
            ONE-INDEX-DFUN-INFO-ACCESSOR-TYPE CHECKING-CACHE
            INTERN-EQL-SPECIALIZER GMAKUNBOUND DO-STANDARD-DEFSETF-1
            FGEN-GENSYMS INFORM-TYPE-SYSTEM-ABOUT-STD-CLASS
            WALKER::GET-IMPLEMENTATION-DEPENDENT-WALKER-TEMPLATE
            ARG-INFO-P WALKER::ENV-LOCK SPECIALIZER-FROM-TYPE
            GET-CONS-GLOBAL-VARIABLE MAKE-CONSTANT-FUNCTION
            MAKE-CALL-METHODS STRUCTURE-TYPE-SLOT-DESCRIPTION-LIST
            VARIABLE-GLOBALLY-SPECIAL-P ONE-INDEX-P
            STRUCTURE-SVUC-METHOD COMPUTE-APPLICABLE-METHODS-EMF-STD-P
            MAKE-FUNCTION-INLINE |LAP Opcode PRINT| CHECKING-FUNCTION
            ONE-INDEX-CACHE MAKE-DEFCLASS-DIRECT-SLOTS-FROM-DEFSTRUCT
            UPDATE-C-A-M-GF-INFO PROTOTYPE-OF-GENERIC-FUNCTION
            ONE-INDEX-ACCESSOR-TYPE %STD-INSTANCE-SLOTS ONE-INDEX-INDEX
            ECD-SUPERCLASS-NAMES EXTRACT-REQUIRED-PARAMETERS
            CLASS-EQ-TYPE EXTRACT-PARAMETERS UPDATE-SLOTS
            CONSTANT-VALUE-DFUN-INFO
            MAKE-STANDARD-INSTANCE-BOUNDP-METHOD-FUNCTION
            MAKE-STRUCTURE-INSTANCE-WRITER-METHOD-FUNCTION
            GENERIC-CLOBBERS-FUNCTION GF-DFUN-INFO MAKE-INITFUNCTION
            |LAP Operand BUILT-IN-OR-STRUCTURE-WRAPPER|
            |LAP Operand FSC-SLOTS| CANONICAL-SLOT-NAME
            UNPARSE-SPECIALIZERS
            MAKE-FUNCALLABLE-STANDARD-INSTANCE-BOUNDP-METHOD-FUNCTION
            ONE-INDEX-DFUN-INFO-P FGEN-SYSTEM
            MAKE-DOCUMENTED-STD-READER-METHOD-FUNCTION STD-INSTANCE-P
            BUILT-IN-WRAPPER-OF
            NON-PCL-OR-AFTER-SHARED-INITIALIZE-METHODS-P
            SLOT-DEFINITION-DEFSTRUCT-SLOT-DESCRIPTION
            LAP-REG-INITIAL-VALUE-FORM GET-BUILT-IN-WRAPPER-SYMBOL
            WALKER::GET-WALKER-TEMPLATE STRUCTURE-SLOTD-ACCESSOR-SYMBOL
            |LAP Operand CDR|
            MAKE-STANDARD-INSTANCE-WRITER-METHOD-FUNCTION
            EARLY-CLASS-DEFINITION ACCESSOR-DFUN-INFO-CACHE
            MAKE-STANDARD-INSTANCE-READER-METHOD-FUNCTION
            SYSTEM:%STRUCTURE-NAME SLOT-SYMBOL-ERROR
            SYSTEM:%COMPILED-FUNCTION-NAME ONE-INDEX-DFUN-INFO-INDEX
            TYPE-FROM-SPECIALIZER MAP-SPECIALIZERS
            MAKE-DOCUMENTED-STD-WRITER-METHOD-FUNCTION
            NON-PCL-OR-AFTER-INITIALIZE-INSTANCE-METHODS-P
            ACCESSOR-DFUN-INFO-ACCESSOR-TYPE ECD-CANONICAL-SLOTS
            STRUCTURE-SLOT-BOUNDP PROCLAIM-INCOMPATIBLE-SUPERCLASSES
            UN-THE MAKE-WRAPPER |LAP Operand USER-SLOTS|
            |LAP Operand CONSTANT| SLOT-READER-UNDEFINED
            USE-DISPATCH-DFUN-P METHOD-LL->GENERIC-FUNCTION-LL
            LIST-LARGE-CACHE
            MAKE-FUNCALLABLE-STANDARD-INSTANCE-READER-METHOD-FUNCTION
            CONSTANT-VALUE-P GF-INFO-SIMPLE-ACCESSOR-TYPE
            SLOT-BOUNDP-UNDEFINED WRAPPER-FOR-STRUCTURE
            MAKE-STRUCTURE-INSTANCE-BOUNDP-METHOD-FUNCTION
            GF-DFUN-CACHE COPY-CACHE ECD-SOURCE CLASS-OF
            EARLY-CLASS-SLOTS MAKE-NOT-FOR-CACHING-METHOD-FUNCTION
            USE-CACHING-DFUN-P INDEX->INDEX-VALUE
            BUILT-IN-OR-STRUCTURE-WRAPPER-FUN FGEN-GENERATOR
            EARLY-UPDATE-DISCRIMINATOR-CODE COUNT-DFUN ONE-CLASS-P
            NON-PCL-INITIALIZE-INSTANCE-METHODS-P
            MAKE-DOCUMENTED-STD-BOUNDP-METHOD-FUNCTION SETFBOUNDP
            |LAP Operand FSC-WRAPPER|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) COMPILE-LAMBDA EXTRACT-DECLARATIONS
            OPCODE GET-FUNCTION OPERAND PARSE-METHOD-OR-SPEC
            MAKE-FINAL-DFUN-INTERNAL PARSE-SPECIALIZED-LAMBDA-LIST
            GET-FUNCTION1 MAP-ALL-CLASSES MAKE-CACHING-DFUN
            MAKE-CONSTANT-VALUE-DFUN WALK-FORM ENSURE-GENERIC-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T (VECTOR T)) T) ALLOCATE-FUNCALLABLE-INSTANCE)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) (VALUES T T)) SYMBOL-APPEND)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) FIND-CLASS ITERATE::FUNCTION-LAMBDA-P
            ITERATE::MAYBE-WARN PRECOMPUTE-EFFECTIVE-METHODS
            LAP-OPERANDS MAKE-SPECIALIZABLE WALKER::RELIST
            LAMBDA-LIST-LEGAL-P MAKE-TYPE-PREDICATE-NAME
            COERCE-TO-CLASS FIND-STRUCTURE-CLASS MAKE-FINAL-DFUN
            GET-METHOD-FUNCTION COMPILE-LAMBDA-DEFERRED
            NO-NEXT-METHOD-TRAP WALKER::RELIST* GET-DFUN-CONSTRUCTOR
            FIND-CLASS-PREDICATE EARLY-METHOD-SPECIALIZERS UPDATE-DFUN
            WALKER::WALKER-ENVIRONMENT-BIND-1 SET-DFUN FIND-CLASS-CELL
            CAPITALIZE-WORDS COMPILE-LAMBDA-UNCOMPILED ENSURE-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) SLOT-VALUE ITERATE::PARSE-DECLARATIONS
            EMIT-WRAPPER-REF *SUBTYPEP SDFUN-FOR-CACHING SAUT-OR-P
            EMIT-CHECKING SAUT-CLASS-EQ-P SAUT-NOT-P COMPUTE-CODE
            EARLY-DFUN FIND-SUPERCLASS-CHAIN COMPUTE-TEST SAUT-EQL-P
            DESTRUCTURE SAUT-CLASS-P SET-FUNCTION-NAME UPDATE-INITS
            CLASS-APPLICABLE-USING-CLASS-P EMIT-CACHING
            EMIT-CACHE-VECTOR-REF GET-NEW-FUNCTION-GENERATOR-INTERNAL
            SPECIALIZER-APPLICABLE-USING-TYPE-P INITIAL-DFUN
            ENSURE-CLASS-VALUES SAUT-AND-P COMPUTE-STD-CPL-PHASE-1
            COMPUTE-APPLICABLE-METHODS-USING-TYPES)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) REMOVE-METHOD SLOT-BOUNDP SLOT-EXISTS-P
            SLOT-MAKUNBOUND SYSTEM::DISPLAY-ENV
            SYSTEM::DISPLAY-COMPILED-ENV
            |LAP Opcode BUILT-IN-INSTANCE-P|
            LOAD-DEFINE-CONSTRUCTOR-CODE-TYPE |LAP Opcode IZEROP|
            ACCESSOR-MISS-FUNCTION BOOTSTRAP-SLOT-INDEX
            %SET-CCLOSURE-ENV PARSE-QUALIFIER-PATTERN
            METHOD-FUNCTION-GET |LAP Operand I-|
            MAKE-EFFECTIVE-METHOD-FUNCTION1
            |LAP Opcode STRUCTURE-INSTANCE-P|
            SET-METHOD-FUNCTION-METHOD WALKER::ENVIRONMENT-FUNCTION
            SUPERCLASSES-COMPATIBLE-P WALKER::ENVIRONMENT-MACRO
            CLASSES-HAVE-COMMON-SUBCLASS-P *TYPEP
            GENERATE-FAST-CLASS-SLOT-ACCESS-P
            |LAP Opcode FSC-INSTANCE-P| LOAD-DEFOPCODE UPDATE-CLASS
            SLOW-SLOT-VALUE |LAP Opcode MOVE| VARIABLE-CLASS SET-SLOTS
            NET-CONSTANT-CONVERTER MAKE-DFUN-LAMBDA-LIST
            METHODS-CONVERTER ADD-ARG-INFO |LAP Operand IREF|
            |SETF PCL FIND-CLASS| |LAP Operand ISHIFT| PERMUTATION-P
            SLOT-WRITER-UNDEFINED COMPUTE-APPLICABLE-METHODS-FUNCTION
            WALKER::VARIABLE-SYMBOL-MACRO-P USER-INSTANCE-ACCESS
            QUALIFIER-CHECK-RUNTIME |LAP Operand ILOGAND|
            MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE
            MAKE-EFFECTIVE-METHOD-FUNCTION-INTERNAL
            MAKE-OPTIMIZED-USER-READER-METHOD-FUNCTION
            FIND-SLOT-DEFINITION CANONICALIZE-SLOT-SPECIFICATION
            ITERATE::SIMPLE-EXPAND-ITERATE-FORM FOUND-UNKNOWN-CLASS
            CANONICALIZE-DEFCLASS-OPTION ITERATE::MV-SETQ
            ITERATE::EXTRACT-SPECIAL-BINDINGS N-N-DFUN-INFO
            MEC-ALL-CLASSES-INTERNAL AUGMENT-TYPE WRAPPER-STATE-TRAP
            SET-WRAPPER |LAP Opcode USER-INSTANCE-P|
            SET-USER-INSTANCE-WRAPPER REMOVE-DIRECT-SUBCLASSES
            SET-USER-INSTANCE-SLOTS FDEFINE-CAREFULLY
            |SETF PCL METHOD-FUNCTION-PLIST| MAKE-PLIST
            REMOVE-SLOT-ACCESSORS CLASS-MIGHT-PRECEDE-P
            WALKER::NOTE-DECLARATION DOCTOR-DFUN-FOR-THE-DEBUGGER
            SET-STANDARD-SVUC-METHOD LOAD-DEFOPERAND REDEFINE-MACRO
            DOCUMENTED-FUNCTION-RETURNING-NIL |LAP Operand I+|
            COMPUTE-INITARG-POSITIONS
            COMPUTE-SECONDARY-DISPATCH-FUNCTION1
            NEW-ARG-INFO-FROM-METHOD SET-GET-METHOD-FROM-IDENTIFIER
            TREE-MEMQ-P MEC-ALL-CLASS-LISTS |SETF PCL GDEFINITION|
            REAL-ADD-METHOD MAKE-DLAP-LAMBDA-LIST
            FUNCALLABLE-STANDARD-INSTANCE-ACCESS CPL-INCONSISTENT-ERROR
            REAL-REMOVE-METHOD EARLY-SORT-METHODS COMPUTE-CONSTANTS
            REMTAIL RAISE-METATYPE CLASS-ON-CLASS-PRECEDENCE-LIST-P
            ADD-DIRECT-SUBCLASSES ADD-SLOT-ACCESSORS
            CLASS-CAN-PRECEDE-P REMOVE-ARG-INFO VARIABLE-LEXICAL-P
            |LAP Operand CREF| VARIABLE-SPECIAL-P COMPUTE-STD-CPL
            DO-SATISFIES-DEFTYPE |LAP Operand ILOGXOR|
            WALKER::NOTE-LEXICAL-BINDING
            ACCESSOR-METHODS-SAFE-TO-USE-SLOT-WRAPPER-OPTIMIZATIONS-P
            |LAP Opcode STD-INSTANCE-P| LIST-EQ
            SET-FUNCALLABLE-INSTANCE-FUNCTION VALUE-FOR-CACHING
            MEC-ALL-CLASSES SAUT-NOT-CLASS-P SAUT-NOT-CLASS-EQ-P
            SET-FUNCTION-PRETTY-ARGLIST REDEFINE-FUNCTION
            SET-STRUCTURE-SVUC-METHOD SAUT-NOT-EQL-P NPERMUTATION-P
            DEAL-WITH-ARGUMENTS-OPTION UPDATE-SLOT-VALUE-GF-INFO
            UPDATE-CPL PRINTING-RANDOM-THING-INTERNAL
            CPL-FORWARD-REFERENCED-CLASS-ERROR CHECKING-DFUN-INFO
            SLOW-SLOT-BOUNDP STANDARD-INSTANCE-ACCESS
            UPDATE-STD-OR-STR-METHODS DESTRUCTURE-INTERNAL
            WALKER::WALK-REPEAT-EVAL SYSTEM:%SET-COMPILED-FUNCTION-NAME
            MAKE-DISCRIMINATING-FUNCTION-ARGLIST
            |SETF PCL FIND-CLASS-PREDICATE| MAKE-UNORDERED-METHODS-EMF
            SLOT-VALUES-SAFE-USING-CLASS-P
            DOCUMENTED-FUNCTION-RETURNING-T PROCLAIM-DEFGENERIC
            ADD-METHOD)) 
(PROCLAIM '(FTYPE (FUNCTION NIL FIXNUM) GET-WRAPPER-CACHE-NUMBER)) 
(IN-PACKAGE "PCL")

(DOLIST (V '(COMPUTE-INSTANCE-LAYOUT |(WRITER DIRECT-DEFAULT-INITARGS)|
                ADD-READER-METHOD
                SHORT-COMBINATION-IDENTITY-WITH-ONE-ARGUMENT
                SLOT-DEFINITION-INITFUNCTION-SIDE-EFFECT-FREE-P
                |DEFINITION-SOURCE-MIXIN class predicate|
                REMOVE-READER-METHOD |(WRITER INTERNAL-SLOTDS)|
                CLASS-FROM-DEFCLASS-P MAKE-CLOSURE-GENERATOR-FORM
                EQL-SPECIALIZER-P |(SETF GENERIC-FUNCTION-NAME)|
                OBJECT-PLIST SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL
                METHOD-IDENTIFIER
                MAKE-DOCUMENTED-BOUNDP-METHOD-FUNCTION
                MAKE-DOCUMENTED-READER-METHOD-FUNCTION
                MAKE-DOCUMENTED-WRITER-METHOD-FUNCTION SPECIALIZER-TYPE
                GF-DFUN-STATE |(SETF GENERIC-FUNCTION-METHOD-CLASS)|
                |(SETF GENERIC-FUNCTION-METHOD-COMBINATION)|
                CLASS-DEFSTRUCT-CONSTRUCTOR DEPENDENT
                |(SETF GENERIC-FUNCTION-METHODS)| TRACE-METHOD
                STORE-CLOSURE-GENERATOR-P |(SETF GF-PRETTY-ARGLIST)|
                METHOD-OPTIMIZED-FUNCTION SPECIALIZERP
                EXACT-CLASS-SPECIALIZER-P
                |STANDARD-OBJECT class predicate|
                COMPATIBLE-META-CLASS-CHANGE-P
                |(BOUNDP READER-FUNCTION)| |(BOUNDP PREDICATE-NAME)|
                |(BOUNDP READERS)| UPDATE-GF-DFUN
                |(BOUNDP DEFSTRUCT-CONC-NAME)|
                |(BOUNDP CLASS-PRECEDENCE-LIST)|
                |(BOUNDP ACCESSOR-FLAGS)|
                |STANDARD-EFFECTIVE-SLOT-DEFINITION class predicate|
                CONSTRUCTOR-SUPPLIED-INITARG-NAMES |(BOUNDP LOCATION)|
                |(BOUNDP DOCUMENTATION)| SPECIALIZER-OBJECT
                |(BOUNDP CACHED-FUNCTIONS-ALIST)|
                |(BOUNDP INCOMPATIBLE-SUPERCLASS-LIST)|
                ACCESSOR-METHOD-SLOT-NAME |(BOUNDP DECLARATIONS)|
                |(BOUNDP CACHED-IN-GENERIC-FUNCTIONS)|
                |(BOUNDP SPECIALIZERS)|
                |STANDARD-DIRECT-SLOT-DEFINITION class predicate|
                |(BOUNDP IDENTIFIER)| SPECIALIZER-CLASS
                |(BOUNDP PRETTY-ARGLIST)|
                |(SETF SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL)|
                CLASS-EQ-SPECIALIZER-P |(BOUNDP NEEDS-NEXT-METHODS-P)|
                SLOTS-FETCHER |(SETF SLOT-ACCESSOR-STD-P)|
                |(BOUNDP INITFUNCTION-SIDE-EFFECT-FREE-P)|
                |STANDARD-SLOT-DEFINITION class predicate|
                REMOVE-WRITER-METHOD |(BOUNDP WRITER-FUNCTION)|
                |(BOUNDP INITFUNCTION)| STRUCTURE-CLASS-P
                |(BOUNDP WRITERS)| |(BOUNDP INITFORM)|
                |(BOUNDP FUNCTION-NAME)| UPDATE-CONSTRUCTORS
                |(BOUNDP SLOT-NAME)| BOUNDP-METHOD-CLASS COMPUTE-LAYOUT
                |(SETF SLOT-DEFINITION-INITARGS)| |(BOUNDP ALLOCATION)|
                CACHED-SLOT-LOCATIONS-AND-FETCHERS-FROM-WRAPPERS
                DOCUMENTATION |(BOUNDP FUNCTION)|
                |(BOUNDP GENERIC-FUNCTION)|
                |SLOT-OBJECT class predicate| |(BOUNDP LAMBDA-LIST)|
                METHOD-PRETTY-ARGLIST |(BOUNDP CAN-PRECEDE-LIST)|
                |(BOUNDP PROTOTYPE)| CLASS-EQ-SPECIALIZER
                INFORM-TYPE-SYSTEM-ABOUT-CLASS
                |PCL-CLASS class predicate| |(BOUNDP DFUN-STATE)|
                |(BOUNDP FROM-DEFCLASS-P)| |(BOUNDP INTERNAL-SLOTD)|
                |(BOUNDP METHOD-CLASS)| |(READER SOURCE)|
                |(BOUNDP METHOD-COMBINATION)|
                |(BOUNDP OPTIMIZED-FUNCTION)|
                |(BOUNDP INTERNAL-WRITER-FUNCTION)|
                |(BOUNDP INTERNAL-READER-FUNCTION)|
                |(BOUNDP OPTIMIZED-SLOT-INDICES)|
                |(BOUNDP DIRECT-METHODS)| |(BOUNDP DIRECT-SLOTS)|
                |(BOUNDP BOUNDP-FUNCTION)|
                |(BOUNDP DIRECT-SUPERCLASSES)|
                |(BOUNDP DIRECT-SUBCLASSES)| ADD-CACHED-FUNCTION
                |(BOUNDP METHODS)| |(BOUNDP OPTIONS)|
                GET-CACHED-FUNCTION GENERIC-FUNCTION-PRETTY-ARGLIST
                MAKE-CONSTRUCTOR-CODE-GENERATORS |(WRITER SOURCE)|
                UPDATE-SLOT-ACCESSOR-FUNCTION
                |SLOT-DEFINITION class predicate|
                |(METHOD NO-NEXT-METHOD (STANDARD-GENERIC-FUNCTION STANDARD-METHOD))|
                MAKE-OPTIMIZED-BOUNDP-METHOD-FUNCTION
                MAKE-OPTIMIZED-READER-METHOD-FUNCTION
                MAKE-OPTIMIZED-WRITER-METHOD-FUNCTION
                |METAOBJECT class predicate| CLASS-PREDICATE-NAME
                LOAD-CONSTRUCTOR-INTERNAL DESCRIBE-OBJECT-SLOTS
                STORE-OPTIMIZED-METHOD-LAMBDA-P COPY-INSTANCE-SLOTS
                CLASSP |STD-CLASS class predicate| LEGAL-QUALIFIERS-P
                ADD-BOUNDP-METHOD LEGAL-LAMBDA-LIST-P
                |SETF PCL GENERIC-FUNCTION-NAME|
                |SETF PCL METHOD-FUNCTION-NAME| LEGAL-DECLARATIONS-P
                |DEPENDENT-UPDATE-MIXIN class predicate|
                |(READER READER-FUNCTION)| |(READER PREDICATE-NAME)|
                |(READER READERS)| |(READER DEFSTRUCT-CONC-NAME)|
                |(READER CLASS-PRECEDENCE-LIST)|
                |(READER ACCESSOR-FLAGS)| |(READER LOCATION)|
                |(READER DOCUMENTATION)| |(SETF CLASS-SLOT-VALUE)|
                |SETF PCL GF-DFUN-STATE|
                |(READER CACHED-FUNCTIONS-ALIST)|
                |(READER INCOMPATIBLE-SUPERCLASS-LIST)|
                |(READER DECLARATIONS)|
                |(READER CACHED-IN-GENERIC-FUNCTIONS)|
                |(READER SPECIALIZERS)| COMPUTE-CLASS-SLOTS
                |(READER IDENTIFIER)| |(READER PRETTY-ARGLIST)|
                |(READER NEEDS-NEXT-METHODS-P)|
                |SETF PCL SLOT-DEFINITION-NAME| |SETF PCL CLASS-NAME|
                |SETF PCL SLOT-DEFINITION-INTERNAL-SLOTD|
                |(WRITER READER-FUNCTION)|
                |(METHOD TRACE-METHOD (STANDARD-METHOD))|
                |(METHOD TRACE-METHOD (TRACED-METHOD))|
                |(METHOD READER-METHOD-CLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-DIRECT-SLOT-DEFINITION))|
                |(METHOD READER-METHOD-CLASS (STANDARD-CLASS STANDARD-DIRECT-SLOT-DEFINITION))|
                |(METHOD CHANGE-CLASS (T SYMBOL))|
                |(WRITER PREDICATE-NAME)| |(WRITER READERS)|
                |(READER INITFUNCTION-SIDE-EFFECT-FREE-P)|
                |(METHOD UPDATE-INSTANCE-FOR-DIFFERENT-CLASS (STANDARD-OBJECT STANDARD-OBJECT))|
                |(METHOD WRAPPER-FETCHER (STRUCTURE-CLASS))|
                |(METHOD WRAPPER-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD CLASS-PROTOTYPE (STRUCTURE-CLASS))|
                |(METHOD CHANGE-CLASS (STANDARD-OBJECT FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD CHANGE-CLASS (STANDARD-OBJECT STANDARD-CLASS))|
                |(METHOD CLASS-SLOT-CELLS (STD-CLASS))|
                |(METHOD CLASS-CONSTRUCTORS (SLOT-CLASS))|
                |(METHOD CLASS-PROTOTYPE (STD-CLASS))|
                |(METHOD WRAPPER-FETCHER (STANDARD-CLASS))|
                |(READER WRITER-FUNCTION)| |(READER INITFUNCTION)|
                |(METHOD DOCUMENTATION (DOCUMENTATION-MIXIN))|
                INITIALIZE-INTERNAL-SLOT-FUNCTIONS
                |(WRITER DEFSTRUCT-CONC-NAME)|
                |SETF PCL SLOT-DEFINITION-TYPE|
                |(SETF METHOD-FUNCTION-NAME)| |(READER WRITERS)|
                |(WRITER CLASS-PRECEDENCE-LIST)|
                |(WRITER ACCESSOR-FLAGS)| |(READER INITFORM)|
                METHOD-COMBINATION-P
                |(METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (SPECIALIZER-WITH-OBJECT))|
                |(METHOD SPECIALIZER-DIRECT-METHODS (SPECIALIZER-WITH-OBJECT))|
                |(WRITER LOCATION)| |(WRITER DOCUMENTATION)|
                |STRUCTURE-DIRECT-SLOT-DEFINITION class predicate|
                |(METHOD ACCESSOR-METHOD-SLOT-DEFINITION (STANDARD-ACCESSOR-METHOD))|
                |(METHOD ACCESSOR-METHOD-SLOT-NAME (TRACED-METHOD))|
                |(READER FUNCTION-NAME)|
                |(METHOD SPECIALIZER-CLASS (EQL-SPECIALIZER))|
                |(METHOD SPECIALIZER-METHOD-TABLE (CLASS-EQ-SPECIALIZER))|
                |(METHOD SPECIALIZER-METHOD-TABLE (EQL-SPECIALIZER))|
                |STRUCTURE-EFFECTIVE-SLOT-DEFINITION class predicate|
                |(METHOD (SETF DOCUMENTATION) (T DOCUMENTATION-MIXIN))|
                |SETF PCL GENERIC-FUNCTION-METHODS|
                |SETF PCL GENERIC-FUNCTION-METHOD-COMBINATION|
                |SETF PCL METHOD-GENERIC-FUNCTION|
                |SETF PCL METHOD-OPTIMIZED-FUNCTION|
                |(METHOD ADD-CONSTRUCTOR (SLOT-CLASS CONSTRUCTOR))|
                |(METHOD ADD-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(METHOD ADD-DIRECT-METHOD (CLASS METHOD))|
                |(READER SLOT-NAME)| |(WRITER CACHED-FUNCTIONS-ALIST)|
                |(WRITER INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL SLOT-ACCESSOR-STD-P|
                |(METHOD UPDATE-CONSTRUCTORS (CLASS))|
                |(METHOD UPDATE-CONSTRUCTORS (SLOT-CLASS))|
                |(METHOD ADD-DIRECT-SUBCLASS (CLASS CLASS))|
                |(READER ALLOCATION)|
                |(METHOD (SETF SLOT-DEFINITION-LOCATION) :AFTER (T STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF SLOT-DEFINITION-BOUNDP-FUNCTION) :AFTER (T EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF SLOT-DEFINITION-WRITER-FUNCTION) :AFTER (T EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF SLOT-DEFINITION-READER-FUNCTION) :AFTER (T EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF SLOT-VALUE-USING-CLASS) (T STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD (SETF SLOT-VALUE-USING-CLASS) (T STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |SETF PCL CONSTRUCTOR-CODE-TYPE|
                |(WRITER DECLARATIONS)|
                |(WRITER CACHED-IN-GENERIC-FUNCTIONS)|
                |(WRITER SPECIALIZERS)|
                |(METHOD SPECIALIZER-CLASS (CLASS))|
                |(METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (CLASS))|
                |(METHOD SPECIALIZER-DIRECT-METHODS (CLASS))|
                |(METHOD (SETF CLASS-NAME) (T STD-CLASS))|
                |(WRITER IDENTIFIER)| |(SETF METHOD-GENERIC-FUNCTION)|
                |(SETF METHOD-OPTIMIZED-FUNCTION)|
                |(WRITER PRETTY-ARGLIST)| LEGAL-SPECIALIZERS-P
                |SETF PCL OBJECT-PLIST|
                |(METHOD REINITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(METHOD INITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(READER FUNCTION)| |(READER GENERIC-FUNCTION)|
                |(WRITER NEEDS-NEXT-METHODS-P)| |(READER LAMBDA-LIST)|
                INITIALIZE-ALLOCATE-STATIC-SLOT-STORAGE-COPY
                |SLOT-CLASS class predicate|
                |SETF PCL SLOT-DEFINITION-INITFORM|
                |(SETF METHOD-CACHED-FUNCTIONS)|
                |(READER CAN-PRECEDE-LIST)|
                |SETF PCL GENERIC-FUNCTION-METHOD-CLASS|
                |(WRITER INITFUNCTION-SIDE-EFFECT-FREE-P)|
                |(READER PROTOTYPE)| |(WRITER WRITER-FUNCTION)|
                |(WRITER INITFUNCTION)|
                |(METHOD REINITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(METHOD WRITER-METHOD-CLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-DIRECT-SLOT-DEFINITION))|
                |(METHOD WRITER-METHOD-CLASS (STANDARD-CLASS STANDARD-DIRECT-SLOT-DEFINITION))|
                |(METHOD REINITIALIZE-INSTANCE (STANDARD-METHOD))|
                |(METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS :AFTER (STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS :AFTER (STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS (EFFECTIVE-SLOT-DEFINITION))|
                |(WRITER WRITERS)| SLOT-ACCESSOR-STD-P
                CLASS-INTERNAL-SLOTDS |(WRITER INITFORM)|
                |(METHOD REINITIALIZE-INSTANCE :AFTER (STRUCTURE-CLASS))|
                |(METHOD INITIALIZE-ALLOCATE-STATIC-SLOT-STORAGE-COPY (STD-CLASS))|
                |(METHOD REINITIALIZE-INSTANCE :AFTER (STD-CLASS))|
                |(METHOD REINITIALIZE-INSTANCE :BEFORE (SLOT-CLASS))|
                |(WRITER FUNCTION-NAME)| |(READER DFUN-STATE)|
                |(READER FROM-DEFCLASS-P)| |SETF PCL GF-PRETTY-ARGLIST|
                OPTIMIZE-INSTANCE-ACCESS
                |SETF PCL SLOT-DEFINITION-LOCATION|
                |SETF PCL SLOT-DEFINITION-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-BOUNDP-FUNCTION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-ALLOCATION|
                |SETF PCL SLOT-DEFINITION-INITFUNCTION|
                |(METHOD MAKE-INSTANCES-OBSOLETE (SYMBOL))|
                |(METHOD MAKE-INSTANCE (SYMBOL))| |(WRITER SLOT-NAME)|
                |(BOUNDP NAME)|
                |(METHOD SAME-SPECIALIZER-P (EQL-SPECIALIZER EQL-SPECIALIZER))|
                |(METHOD SAME-SPECIALIZER-P (CLASS-EQ-SPECIALIZER CLASS-EQ-SPECIALIZER))|
                |(METHOD SAME-SPECIALIZER-P (SPECIALIZER SPECIALIZER))|
                |(READER INTERNAL-SLOTD)|
                |(METHOD MAKE-DIRECT-SLOTD (STRUCTURE-CLASS))|
                |(METHOD MAKE-CLASS-PROTOTYPE (STRUCTURE-CLASS))|
                |(METHOD MAKE-INSTANCES-OBSOLETE (STD-CLASS))|
                |(METHOD MAKE-DIRECT-SLOTD (STD-CLASS))|
                |(METHOD MAKE-CLASS-PROTOTYPE (STD-CLASS))|
                |(METHOD MAKE-INSTANCE (SLOT-CLASS))|
                |(WRITER ALLOCATION)| CACHED-FUNCTIONS
                |(READER METHOD-CLASS)| |(SETF OBJECT-PLIST)|
                |(METHOD SLOTS-TO-INSPECT (SLOT-CLASS SLOT-OBJECT))|
                |(METHOD ALLOCATE-INSTANCE (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (SLOT-CLASS FORWARD-REFERENCED-CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (CLASS BUILT-IN-CLASS))|
                |(METHOD VALIDATE-SUPERCLASS (CLASS CLASS))|
                |(METHOD ALLOCATE-INSTANCE (STRUCTURE-CLASS))|
                |(METHOD ALLOCATE-INSTANCE (STANDARD-CLASS))|
                |(READER METHOD-COMBINATION)|
                |(READER OPTIMIZED-FUNCTION)|
                |(READER INTERNAL-WRITER-FUNCTION)|
                |(READER INTERNAL-READER-FUNCTION)|
                METHOD-COMBINATION-OPTIONS
                |(READER OPTIMIZED-SLOT-INDICES)|
                |(METHOD COMPUTE-CONSTRUCTOR-CODE (SLOT-CLASS CONSTRUCTOR))|
                |(METHOD REMOVE-CONSTRUCTOR (SLOT-CLASS CONSTRUCTOR))|
                |(METHOD COMPUTE-DISCRIMINATING-FUNCTION (STANDARD-GENERIC-FUNCTION))|
                |(METHOD COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO (STANDARD-GENERIC-FUNCTION))|
                |(METHOD REMOVE-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(METHOD REMOVE-DIRECT-METHOD (CLASS METHOD))|
                |(READER DIRECT-METHODS)| |(READER DIRECT-SLOTS)|
                |SETF PCL SLOT-DEFINITION-READERS|
                |(METHOD COPY-INSTANCE-SLOTS (SLOT-OBJECT SLOT-OBJECT))|
                |(METHOD SAME-SPECIALIZER-P (CLASS CLASS))|
                |(METHOD COMPUTE-CLASS-PRECEDENCE-LIST (SLOT-CLASS))|
                |(METHOD COMPUTE-SLOTS :AROUND (STRUCTURE-CLASS))|
                |(METHOD COMPUTE-SLOTS (STRUCTURE-CLASS))|
                |(METHOD COMPUTE-SLOTS :AROUND (STD-CLASS))|
                |(METHOD COMPUTE-SLOTS (STD-CLASS))|
                |(METHOD COMPUTE-DEFAULT-INITARGS (SLOT-CLASS))|
                |(METHOD REMOVE-DIRECT-SUBCLASS (CLASS CLASS))|
                |(WRITER FUNCTION)| |(WRITER GENERIC-FUNCTION)|
                |STRUCTURE-OBJECT class predicate|
                COMPILE-STRUCTURE-CLASS-INTERNALS
                |(READER BOUNDP-FUNCTION)| |SETF PCL DOCUMENTATION|
                |(READER DIRECT-SUPERCLASSES)|
                |(READER DIRECT-SUBCLASSES)|
                |(METHOD GENERIC-FUNCTION-PRETTY-ARGLIST (STANDARD-GENERIC-FUNCTION))|
                |(METHOD FUNCTION-KEYWORDS (STANDARD-METHOD))|
                |(SETF GF-VALID-P)| |(WRITER LAMBDA-LIST)|
                FUNCALLABLE-STANDARD-CLASS-P |(BOUNDP CLASS)|
                |(METHOD FINALIZE-INHERITANCE (STRUCTURE-CLASS))|
                |(METHOD FINALIZE-INHERITANCE (STD-CLASS))|
                |(METHOD SLOT-DEFINITION-ALLOCATION (STRUCTURE-SLOT-DEFINITION))|
                |(METHOD SLOT-VALUE-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-BOUNDP-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-MAKUNBOUND-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-EXISTS-P-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-VALUE-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-BOUNDP-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(METHOD SLOT-MAKUNBOUND-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(READER METHODS)| |(READER OPTIONS)|
                |(WRITER CAN-PRECEDE-LIST)|
                |SETF PCL SLOT-DEFINITION-CLASS|
                |SETF PCL SLOT-VALUE-USING-CLASS| |(WRITER PROTOTYPE)|
                |(BOUNDP TYPE)| |(BOUNDP OBJECT)|
                CLASS-CAN-PRECEDE-LIST
                |(METHOD SLOTS-FETCHER (STRUCTURE-CLASS))|
                |(METHOD SLOTS-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD SLOTS-FETCHER (STANDARD-CLASS))|
                SLOT-ACCESSOR-FUNCTION METHOD-OPTIMIZED-METHOD-LAMBDA
                METHOD-CONSTANT-VALUE |(BOUNDP PLIST)|
                |SETF PCL CLASS-INCOMPATIBLE-SUPERCLASS-LIST|
                |SETF PCL SLOT-DEFINITION-WRITERS|
                |(WRITER DFUN-STATE)| |(WRITER FROM-DEFCLASS-P)|
                |(BOUNDP SLOTS)|
                |STRUCTURE-SLOT-DEFINITION class predicate|
                LEGAL-METHOD-FUNCTION-P |(WRITER INTERNAL-SLOTD)|
                METHOD-CACHED-FUNCTIONS
                |(METHOD INSTALL-LAZY-CONSTRUCTOR-INSTALLER (CONSTRUCTOR))|
                CLASS-DEFSTRUCT-CONC-NAME |(WRITER METHOD-CLASS)|
                |(METHOD ENSURE-CLASS-USING-CLASS (T PCL-CLASS))|
                GET-METHOD |(WRITER METHOD-COMBINATION)|
                |(WRITER OPTIMIZED-FUNCTION)|
                |(WRITER INTERNAL-WRITER-FUNCTION)|
                |(WRITER INTERNAL-READER-FUNCTION)|
                |(WRITER OPTIMIZED-SLOT-INDICES)|
                |(METHOD METHOD-QUALIFIERS (TRACED-METHOD))|
                |(METHOD METHOD-SPECIALIZERS (TRACED-METHOD))|
                |(METHOD METHOD-LAMBDA-LIST (TRACED-METHOD))|
                |(METHOD METHOD-PRETTY-ARGLIST (STANDARD-METHOD))|
                |(METHOD METHOD-CONSTANT-VALUE (STANDARD-METHOD))|
                |(METHOD METHOD-QUALIFIERS (STANDARD-METHOD))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING-P (STANDARD-ACCESSOR-METHOD))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING-P (STANDARD-METHOD))|
                |(METHOD METHOD-CACHED-FUNCTIONS (STANDARD-METHOD))|
                |(WRITER DIRECT-METHODS)| |(WRITER DIRECT-SLOTS)|
                |(WRITER BOUNDP-FUNCTION)|
                |(WRITER DIRECT-SUPERCLASSES)|
                |(WRITER DIRECT-SUBCLASSES)|
                SLOT-DEFINITION-INTERNAL-SLOTD
                |(METHOD BOUNDP-METHOD-CLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-DIRECT-SLOT-DEFINITION))|
                |(METHOD BOUNDP-METHOD-CLASS (STANDARD-CLASS STANDARD-DIRECT-SLOT-DEFINITION))|
                |(WRITER METHODS)| |(WRITER OPTIONS)|
                SHORT-METHOD-COMBINATION-P GF-ARG-INFO
                |(METHOD RAW-INSTANCE-ALLOCATOR (FUNCALLABLE-STANDARD-CLASS))|
                |(METHOD RAW-INSTANCE-ALLOCATOR (STANDARD-CLASS))|
                SEQUENCEP SPECIALIZER-METHOD-TABLE
                |(METHOD MAYBE-UPDATE-CONSTRUCTORS (GENERIC-FUNCTION METHOD))|
                METHOD-CLOSURE-GENERATOR REMOVE-CONSTRUCTOR
                GF-PRETTY-ARGLIST SAME-SPECIALIZER-P CONSTRUCTOR-NAME
                DO-DEFSTRUCT-FROM-DEFCLASS
                SLOT-DEFINITION-BOUNDP-FUNCTION
                SLOT-DEFINITION-WRITER-FUNCTION
                SLOT-DEFINITION-READER-FUNCTION
                SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION
                SLOT-DEFINITION-INTERNAL-READER-FUNCTION
                CONSTRUCTOR-CODE-TYPE
                MAKE-CACHED-METHOD-LAMBDA-FROM-STORED-LAMBDA
                MAKE-CACHED-METHOD-FUNCTION-FROM-STORED-LAMBDA
                METHOD-OPTIMIZED-SLOT-INDICES ADD-CONSTRUCTOR
                SLOT-DEFINITION-CLASS GET-CONSTRUCTOR
                EQL-SPECIALIZER-OBJECT CLASS-CONSTRUCTORS
                STORE-METHOD-FUNCTION-P
                STORE-METHOD-OPTIMIZED-FUNCTION-P |(BOUNDP WRAPPER)|
                SLOTS-TO-INSPECT |(BOUNDP DEFSTRUCT-ACCESSOR-SYMBOL)|
                SPECIALIZER-DIRECT-GENERIC-FUNCTIONS
                |(BOUNDP CLASS-EQ-SPECIALIZER)|
                |(SETF SLOT-DEFINITION-NAME)| ADD-WRITER-METHOD
                |(BOUNDP ARGUMENT-PRECEDENCE-ORDER)|
                |(BOUNDP SIDE-EFFECT-INTERNAL-SLOTDS)|
                |(SETF SLOT-DEFINITION-INTERNAL-SLOTD)|
                |(BOUNDP ARG-INFO)| CONSTRUCTOR-CLASS
                |(SETF SLOT-DEFINITION-INITFUNCTION-SIDE-EFFECT-FREE-P)|
                |(SETF SLOT-DEFINITION-CLASS)|
                |(SETF SLOT-VALUE-USING-CLASS)|
                |(BOUNDP DEFAULT-INITARGS)|
                |(SETF SLOT-DEFINITION-ALLOCATION)|
                |(SETF SLOT-DEFINITION-BOUNDP-FUNCTION)|
                |(SETF SLOT-DEFINITION-INITFUNCTION)|
                |(SETF SLOT-DEFINITION-INTERNAL-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION)|
                |(SETF SLOT-DEFINITION-LOCATION)|
                |(SETF SLOT-DEFINITION-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-WRITER-FUNCTION)|
                |(BOUNDP DEFSTRUCT-CONSTRUCTOR)|
                |(SETF SLOT-DEFINITION-READERS)|
                |(SETF SLOT-DEFINITION-WRITERS)|
                MAYBE-UPDATE-CONSTRUCTORS |(SETF SLOT-DEFINITION-TYPE)|
                CONSTRUCTOR-CODE-GENERATORS
                |(SETF SLOT-DEFINITION-INITFORM)|
                |EFFECTIVE-SLOT-DEFINITION class predicate|
                MAKE-CLASS-PROTOTYPE |(BOUNDP VALID-P)|
                |(BOUNDP INITARGS)| LONG-METHOD-COMBINATION-FUNCTION
                |BUILT-IN-CLASS class predicate| GENERIC-FUNCTION-P
                MAKE-OPTIMIZED-METHOD-LAMBDA |(BOUNDP FINALIZED-P)|
                |(BOUNDP OPTIMIZED-METHOD-LAMBDA)| |(READER NAME)|
                |(BOUNDP CLOSURE-GENERATOR)| |(READER CLASS)|
                |(BOUNDP DIRECT-DEFAULT-INITARGS)| LEGAL-SLOT-NAME-P
                |(READER TYPE)| |(READER OBJECT)|
                |(METHOD DO-DEFSTRUCT-FROM-DEFCLASS (STRUCTURE-CLASS T T T T T))|
                CLASS-WRAPPER |(READER PLIST)| GF-VALID-P
                |(METHOD NO-APPLICABLE-METHOD (T))| |(READER SLOTS)|
                |(BOUNDP INTERNAL-SLOTDS)| |(WRITER NAME)|
                DEFINITION-SOURCE DEFAULT-INITARGS |(WRITER CLASS)|
                CLASS-SLOT-VALUE |(WRITER TYPE)| |(WRITER OBJECT)|
                |(WRITER PLIST)| |(WRITER SLOTS)|
                FORWARD-REFERENCED-CLASS-P
                CLASS-SIDE-EFFECT-INTERNAL-SLOTDS
                |SPECIALIZER-WITH-OBJECT class predicate|
                LEGAL-QUALIFIER-P METHOD-P
                |PLIST-MIXIN class predicate| MAKE-DIRECT-SLOTD
                CLASS-SLOT-CELLS COMPUTE-CONSTRUCTOR-CODE
                |(METHOD LOAD-CONSTRUCTOR-INTERNAL (SLOT-CLASS T T T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STANDARD-GENERIC-FUNCTION T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (STANDARD-GENERIC-FUNCTION T))|
                |(METHOD READER-METHOD-CLASS (SLOT-CLASS T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STANDARD-METHOD T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (STANDARD-ACCESSOR-METHOD T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (STANDARD-METHOD T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-SLOT-DEFINITION T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STANDARD-SLOT-DEFINITION T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-CLASS T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (BUILT-IN-CLASS T))|
                |(METHOD READER-METHOD-CLASS (T T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (CLASS T))|
                |(METHOD SHARED-INITIALIZE :AFTER (STD-CLASS T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (STD-CLASS T))|
                |(METHOD SHARED-INITIALIZE :AFTER (EQL-SPECIALIZER T))|
                |(METHOD SHARED-INITIALIZE :AFTER (CLASS-EQ-SPECIALIZER T))|
                |(METHOD SHARED-INITIALIZE :BEFORE (DOCUMENTATION-MIXIN T))|
                |(METHOD SHARED-INITIALIZE (SLOT-OBJECT T))|
                |(METHOD CLASS-SLOT-VALUE (STD-CLASS T))|
                STANDARD-ACCESSOR-METHOD-P |(SETF CLASS-NAME)|
                |(METHOD CACHED-SLOT-LOCATIONS-AND-FETCHERS-FROM-WRAPPERS (STANDARD-METHOD T))|
                |(METHOD UPDATE-GF-DFUN (STD-CLASS T))|
                |(METHOD ADD-CACHED-FUNCTION (STANDARD-METHOD T T))|
                |(METHOD ADD-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                |(METHOD ADD-BOUNDP-METHOD (SLOT-CLASS T T))|
                |(METHOD ADD-WRITER-METHOD (SLOT-CLASS T T))|
                |(METHOD ADD-READER-METHOD (SLOT-CLASS T T))|
                |(METHOD UPDATE-SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T T))|
                |(METHOD UPDATE-INSTANCE-FOR-REDEFINED-CLASS (STANDARD-OBJECT T T T))|
                STANDARD-GENERIC-FUNCTION-P STANDARD-METHOD-P
                STANDARD-READER-METHOD-P |(METHOD DOCUMENTATION (T))|
                |(READER WRAPPER)|
                |(METHOD (SETF DOCUMENTATION) (T T))|
                |(METHOD (SETF SLOT-ACCESSOR-STD-P) (T EFFECTIVE-SLOT-DEFINITION T))|
                |(METHOD (SETF CLASS-SLOT-VALUE) (T STD-CLASS T))|
                |SETF PCL GF-VALID-P|
                |(READER DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STRUCTURE-CLASS T))|
                |(METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STD-CLASS T))|
                |(METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                |(METHOD DEFAULT-INITARGS (SLOT-CLASS T T))|
                |(READER CLASS-EQ-SPECIALIZER)|
                COMPUTE-DEFAULT-INITARGS
                COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS
                |(METHOD LEGAL-LAMBDA-LIST-P (STANDARD-GENERIC-FUNCTION T))|
                |(METHOD LEGAL-DECLARATIONS-P (STANDARD-GENERIC-FUNCTION T))|
                |(METHOD LEGAL-SPECIALIZER-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-SPECIALIZERS-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-SLOT-NAME-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-QUALIFIER-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-QUALIFIERS-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-METHOD-FUNCTION-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-LAMBDA-LIST-P (STANDARD-METHOD T))|
                |(METHOD LEGAL-DOCUMENTATION-P (DOCUMENTATION-MIXIN T))|
                |(SETF CLASS-INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL CLASS-SLOT-VALUE|
                |(READER ARGUMENT-PRECEDENCE-ORDER)|
                |(READER SIDE-EFFECT-INTERNAL-SLOTDS)|
                |(METHOD PRINT-OBJECT (CONSTRUCTOR T))|
                |(METHOD PRINT-OBJECT (METHOD-COMBINATION T))|
                |(METHOD PRINT-OBJECT (GENERIC-FUNCTION T))|
                |(METHOD WRITER-METHOD-CLASS (SLOT-CLASS T))|
                |(METHOD PRINT-OBJECT (STANDARD-ACCESSOR-METHOD T))|
                |(METHOD PRINT-OBJECT (STANDARD-METHOD T))|
                |(METHOD PRINT-OBJECT (SLOT-DEFINITION T))|
                |(METHOD PRINT-OBJECT (CLASS T))|
                |(METHOD PRINT-OBJECT (T T))|
                |(METHOD WRITER-METHOD-CLASS (T T))|
                |(METHOD TRACE-METHOD (CONS))| |(READER ARG-INFO)|
                METHOD-COMBINATION-TYPE
                |SETF PCL SLOT-DEFINITION-INITFUNCTION-SIDE-EFFECT-FREE-P|
                |(READER DEFAULT-INITARGS)|
                CLASS-CACHED-IN-GENERIC-FUNCTIONS
                |(READER DEFSTRUCT-CONSTRUCTOR)|
                |(METHOD MAKE-CACHED-METHOD-LAMBDA-FROM-STORED-LAMBDA (STANDARD-METHOD T))|
                |(METHOD MAKE-CONSTRUCTOR-CODE-GENERATORS (SLOT-CLASS T T T T))|
                |(METHOD MAKE-CLOSURE-GENERATOR-FORM (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T T))|
                |(METHOD MAKE-OPTIMIZED-METHOD-LAMBDA (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T T))|
                |(METHOD MAKE-METHOD-LAMBDA (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T T))|
                |(METHOD MAKE-CACHED-METHOD-FUNCTION-FROM-STORED-LAMBDA (STANDARD-METHOD T))|
                |(METHOD MAKE-OPTIMIZED-BOUNDP-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-WRITER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-READER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-BOUNDP-METHOD-FUNCTION (STRUCTURE-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-WRITER-METHOD-FUNCTION (STRUCTURE-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-READER-METHOD-FUNCTION (STRUCTURE-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-BOUNDP-METHOD-FUNCTION (STANDARD-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-WRITER-METHOD-FUNCTION (STANDARD-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-READER-METHOD-FUNCTION (STANDARD-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-WRITER-METHOD-FUNCTION (SLOT-CLASS T T T))|
                |(METHOD MAKE-OPTIMIZED-READER-METHOD-FUNCTION (SLOT-CLASS T T T))|
                |(METHOD MAKE-DOCUMENTED-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T T T))|
                |(METHOD MAKE-DOCUMENTED-WRITER-METHOD-FUNCTION (SLOT-CLASS T T T))|
                |(METHOD MAKE-DOCUMENTED-READER-METHOD-FUNCTION (SLOT-CLASS T T T))|
                |(WRITER WRAPPER)| STANDARD-CLASS-P
                |(SETF CONSTRUCTOR-CODE-TYPE)| LEGAL-SPECIALIZER-P
                |(WRITER DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION LONG-METHOD-COMBINATION T))|
                |(METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION SHORT-METHOD-COMBINATION T))|
                |(METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION STANDARD-METHOD-COMBINATION T))|
                |(METHOD COMPUTE-APPLICABLE-METHODS-USING-CLASSES (GENERIC-FUNCTION T))|
                |(METHOD COMPUTE-APPLICABLE-METHODS (GENERIC-FUNCTION T))|
                |(METHOD REMOVE-NAMED-METHOD (T T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS :AROUND (STRUCTURE-CLASS T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (STRUCTURE-CLASS T T))|
                |(METHOD COMPILE-STRUCTURE-CLASS-INTERNALS (STRUCTURE-CLASS T T T T))|
                |(METHOD REMOVE-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                |(METHOD COMPATIBLE-META-CLASS-CHANGE-P (T T))|
                |(METHOD REMOVE-BOUNDP-METHOD (SLOT-CLASS T))|
                |(METHOD REMOVE-WRITER-METHOD (SLOT-CLASS T))|
                |(METHOD REMOVE-READER-METHOD (SLOT-CLASS T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS (SLOT-CLASS T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (FUNCALLABLE-STANDARD-CLASS T T))|
                |(METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (STANDARD-CLASS T T))|
                |(METHOD COMPUTE-LAYOUT (STD-CLASS T T))|
                |(METHOD COMPUTE-CLASS-SLOTS (STD-CLASS T))|
                |(METHOD COMPUTE-INSTANCE-LAYOUT (STD-CLASS T))|
                |(METHOD COMPUTE-STORAGE-INFO (STD-CLASS T))|
                COMPUTE-STORAGE-INFO |(READER VALID-P)|
                |DIRECT-SLOT-DEFINITION class predicate|
                METHOD-FUNCTION-NAME |(READER INITARGS)|
                |(WRITER CLASS-EQ-SPECIALIZER)|
                |(METHOD FIND-METHOD-COMBINATION (GENERIC-FUNCTION (EQL STANDARD) T))|
                STANDARD-BOUNDP-METHOD-P METHOD-FUNCTION-FOR-CACHING
                |(METHOD STORE-OPTIMIZED-METHOD-LAMBDA-P (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T))|
                |(METHOD STORE-CLOSURE-GENERATOR-P (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T))|
                |(METHOD STORE-METHOD-OPTIMIZED-FUNCTION-P (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T))|
                |(METHOD STORE-METHOD-FUNCTION-P (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T))|
                |(METHOD SLOT-UNBOUND :AROUND (CLASS T T))|
                |(METHOD SLOT-ACCESSOR-STD-P (EFFECTIVE-SLOT-DEFINITION T))|
                |(METHOD SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T))|
                |(METHOD SLOT-MISSING (T T T T))|
                |(METHOD SLOT-UNBOUND (T T T))| |(READER FINALIZED-P)|
                |(SETF DOCUMENTATION)|
                |SETF PCL METHOD-CACHED-FUNCTIONS|
                RAW-INSTANCE-ALLOCATOR
                |(WRITER ARGUMENT-PRECEDENCE-ORDER)|
                INSTALL-LAZY-CONSTRUCTOR-INSTALLER
                |(WRITER SIDE-EFFECT-INTERNAL-SLOTDS)|
                |(METHOD MAP-DEPENDENTS (DEPENDENT-UPDATE-MIXIN T))|
                METHOD-FUNCTION-FOR-CACHING-P
                |SETF PCL SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL|
                |(WRITER ARG-INFO)| |(READER OPTIMIZED-METHOD-LAMBDA)|
                COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO
                STANDARD-WRITER-METHOD-P
                CLASS-INCOMPATIBLE-SUPERCLASS-LIST
                |(WRITER DEFAULT-INITARGS)|
                |(WRITER DEFSTRUCT-CONSTRUCTOR)|
                |(METHOD DIRECT-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(METHOD DIRECT-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                WRAPPER-FETCHER |(METHOD DESCRIBE-OBJECT (CLASS T))|
                |(METHOD DESCRIBE-OBJECT (STANDARD-GENERIC-FUNCTION T))|
                |(METHOD DESCRIBE-OBJECT-SLOTS (SLOT-OBJECT T))|
                |(METHOD DESCRIBE-OBJECT (SLOT-OBJECT T))|
                |(METHOD DESCRIBE-OBJECT (T T))|
                |(METHOD DESCRIBE-OBJECT (CONSTRUCTOR T))|
                |SETF PCL SLOT-DEFINITION-INITARGS|
                |(READER CLOSURE-GENERATOR)| REMOVE-BOUNDP-METHOD
                |(METHOD GET-CONSTRUCTOR (SLOT-CLASS T))|
                |(METHOD OPTIMIZE-INSTANCE-ACCESS (STANDARD-GENERIC-FUNCTION STANDARD-METHOD STRUCTURE-CLASS T T T T T))|
                |(METHOD OPTIMIZE-INSTANCE-ACCESS (STANDARD-GENERIC-FUNCTION STANDARD-METHOD T T T T T T))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING (STANDARD-ACCESSOR-METHOD T))|
                |(METHOD GET-CACHED-FUNCTION (STANDARD-METHOD T))|
                |(METHOD METHOD-FUNCTION-FOR-CACHING (STANDARD-METHOD T))|
                |(WRITER VALID-P)| |(WRITER INITARGS)|
                |(METHOD BOUNDP-METHOD-CLASS (SLOT-CLASS T))|
                |(METHOD BOUNDP-METHOD-CLASS (T T))|
                |(WRITER FINALIZED-P)|
                |(READER DIRECT-DEFAULT-INITARGS)| |(BOUNDP SOURCE)|
                |DOCUMENTATION-MIXIN class predicate|
                |(WRITER OPTIMIZED-METHOD-LAMBDA)|
                |(SETF GF-DFUN-STATE)| |(READER INTERNAL-SLOTDS)|
                SHORT-COMBINATION-OPERATOR METHOD-NEEDS-NEXT-METHODS-P
                |(WRITER CLOSURE-GENERATOR)| REMOVE-NAMED-METHOD
                |(METHOD ENSURE-CLASS-USING-CLASS (T NULL))|
                LEGAL-DOCUMENTATION-P CLASS-DIRECT-SUPERCLASSES
                CLASS-DIRECT-SUBCLASSES CLASS-DIRECT-DEFAULT-INITARGS
                SLOT-DEFINITION-READERS SLOT-VALUE-USING-CLASS
                DESCRIBE-OBJECT COMPUTE-APPLICABLE-METHODS CLASS-NAME
                CLASS-PROTOTYPE READER-METHOD-CLASS REMOVE-METHOD
                SLOT-DEFINITION-INITFORM
                UPDATE-INSTANCE-FOR-REDEFINED-CLASS
                UPDATE-INSTANCE-FOR-DIFFERENT-CLASS CHANGE-CLASS
                METHOD-FUNCTION DIRECT-SLOT-DEFINITION-CLASS
                MAKE-METHOD-LAMBDA EFFECTIVE-SLOT-DEFINITION-CLASS
                CLASS-SLOTS COMPUTE-SLOTS SLOT-DEFINITION-NAME
                FINALIZE-INHERITANCE
                GENERIC-FUNCTION-ARGUMENT-PRECEDENCE-ORDER
                GENERIC-FUNCTION-LAMBDA-LIST NO-NEXT-METHOD
                CLASS-DIRECT-SLOTS CLASS-DEFAULT-INITARGS
                COMPUTE-DISCRIMINATING-FUNCTION CLASS-FINALIZED-P
                GENERIC-FUNCTION-NAME REMOVE-DEPENDENT
                COMPUTE-CLASS-PRECEDENCE-LIST ADD-DEPENDENT
                SLOT-BOUNDP-USING-CLASS ACCESSOR-METHOD-SLOT-DEFINITION
                SHARED-INITIALIZE ADD-DIRECT-METHOD
                SLOT-DEFINITION-LOCATION SLOT-DEFINITION-INITFUNCTION
                SLOT-DEFINITION-ALLOCATION ADD-METHOD
                GENERIC-FUNCTION-METHOD-CLASS METHOD-SPECIALIZERS
                SLOT-DEFINITION-INITARGS WRITER-METHOD-CLASS
                ADD-DIRECT-SUBCLASS SPECIALIZER-DIRECT-METHODS
                GENERIC-FUNCTION-METHOD-COMBINATION ALLOCATE-INSTANCE
                COMPUTE-EFFECTIVE-METHOD SLOT-DEFINITION-TYPE
                SLOT-UNBOUND INITIALIZE-INSTANCE FUNCTION-KEYWORDS
                SLOT-EXISTS-P-USING-CLASS REINITIALIZE-INSTANCE
                VALIDATE-SUPERCLASS GENERIC-FUNCTION-METHODS
                REMOVE-DIRECT-METHOD METHOD-LAMBDA-LIST MAKE-INSTANCE
                GENERIC-FUNCTION-DECLARATIONS
                COMPUTE-EFFECTIVE-SLOT-DEFINITION PRINT-OBJECT
                METHOD-QUALIFIERS METHOD-GENERIC-FUNCTION
                REMOVE-DIRECT-SUBCLASS MAKE-INSTANCES-OBSOLETE
                SLOT-MAKUNBOUND-USING-CLASS
                ENSURE-GENERIC-FUNCTION-USING-CLASS SLOT-MISSING
                MAP-DEPENDENTS FIND-METHOD-COMBINATION
                ENSURE-CLASS-USING-CLASS NO-APPLICABLE-METHOD
                SLOT-DEFINITION-WRITERS
                COMPUTE-APPLICABLE-METHODS-USING-CLASSES
                CLASS-PRECEDENCE-LIST))
  (SETF (GET V 'COMPILER::PROCLAIMED-CLOSURE) T)) 
