(load "core800.lisp")

(defun show-ascii-art ()
  (write-line "         ___     _,.--.,_")
  (write-line "      .-~   ~--\"~-.   ._ \"-.")
  (write-line "     /      ./_    Y    \"-. \\")
  (write-line "    Y       :~     !         Y")
  (write-line "    lq p    |     /         .|")
  (write-line " _   \\. .-, l    /          |j")
  (write-line "()\\___) |/   \\_/\";          !")
  (write-line " \\._____.-~\\  .  ~\\.      ./")
  (write-line "            Y_ Y_.\"vr\"~  T")
  (write-line "            (  (    |L    j")
  (write-line "            [nn[nn..][nn..]"))
(show-ascii-art)
(read-eval-print-loop)
