#2012-12-05 20:59:45 +0100	<pjb>	dim: gcc -m32 -o lisp500 lisp500.c -ldl -lm && ./lisp500
#2012-12-05 21:00:04 +0100	<pjb>	It must be compiled in 32-bit.
# dmailes says dont forget to
#   apt-get install libc6-dev-i386 linux-libc-dev:i386 linux-libc-dev



lisp500 : lisp500.o
	gcc -m32 -o lisp500 lisp500.o

lisp500.o : lisp500.c
	gcc -c -m32 lisp500.c

clean :
	rm lisp500 lisp500.o

