
ecoffdump:	ecoffdump.c
	gcc -o ecoffdump ecoffdump.c

coffdump:	coffdump.c
	cc -o coffdump coffdump.c -lld

test-dld:	test-dld.c
	cc -o test-dld test-dld.c

dld:	dld.c
	cc -o dld dld.c -lld

try:	try.c
	cc -o try try.c -D${MACHINE}
